services:
  pgdatabase:
    networks: 
      - postgres
    image: postgres:13
    hostname: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    networks: 
      - postgres
    image: dpage/pgadmin4
    volumes:
      - ./data_pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT=1
      - PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT='False'
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED='False'
    ports:
      - "8080:80"
    depends_on: 
      - pgdatabase
    
volumes:
  pgadmin:

networks:
  postgres:
